spring:
  application:
    name: springsecuritymaster

  datasource:
    url: jdbc:h2:tcp://localhost:9099/~/securitydb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  thymeleaf:
    cache: false